[package]
name = "xtranslator-tauri"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
tauri-plugin-dialog = "2.0"
tokio = { version = "1", features = ["full"] }
serde = { workspace = true }
serde_json = "1.0"
xt-core = { path = "../crates/xt-core" }
xt-shared = { path = "../crates/xt-shared" }
reqwest = { workspace = true }
regex = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
